In [2]:
import torch
a = torch.empty(3,4)
print(a)

tensor([[1.5721e-35, 0.0000e+00, 3.3631e-44, 0.0000e+00],
        [       nan, 0.0000e+00, 1.1578e+27, 1.1362e+30],
        [7.1547e+22, 4.5828e+30, 1.2121e+04, 7.1846e+22]])


In [5]:
b = torch.randn(3,4)
print(b)

tensor([[-0.5474, -1.2399, -1.6423,  0.0327],
        [ 0.3637, -2.8998, -0.6737,  1.9290],
        [-0.0236, -0.5199, -0.2277, -0.7489]])


In [7]:
c = torch.zeros(3,4)
print(c)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [10]:
d = torch.tensor([[1,2],[3,4]])
print(d)

tensor([[1, 2],
        [3, 4]])


In [11]:
print(a.dtype)
print(d.dtype)

torch.float32
torch.int64


In [12]:
print(b)
print(b.device)
b = b.to('cuda')
print(b)
print(b.device)

tensor([[-0.5474, -1.2399, -1.6423,  0.0327],
        [ 0.3637, -2.8998, -0.6737,  1.9290],
        [-0.0236, -0.5199, -0.2277, -0.7489]])
cpu
tensor([[-0.5474, -1.2399, -1.6423,  0.0327],
        [ 0.3637, -2.8998, -0.6737,  1.9290],
        [-0.0236, -0.5199, -0.2277, -0.7489]], device='cuda:0')
cuda:0


In [16]:
a = torch.zeros(3,4)
b = torch.ones(3,4)
print(a+b)
print(a-b)
print(a/b)
print(a*b)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[-1., -1., -1., -1.],
        [-1., -1., -1., -1.],
        [-1., -1., -1., -1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [15]:
a = torch.randn(3,4)
b = torch.randn(4,3)
print(torch.mm(a,b))
print(a@b)

tensor([[-2.7942,  1.4318, -0.0096],
        [ 0.5128, -0.0603,  1.3429],
        [ 1.4689,  3.5385, -0.0242]])
tensor([[-2.7942,  1.4318, -0.0096],
        [ 0.5128, -0.0603,  1.3429],
        [ 1.4689,  3.5385, -0.0242]])


In [18]:
a = torch.randn(3,4)
b = torch.randn(3,5)
c = torch.cat((a,b),dim=-1)
print(c.size())

torch.Size([3, 9])


In [19]:
a = torch.randn(1,2,3)
a = torch.squeeze(a)
print(a.size())
a = torch.unsqueeze(a,0)
print(a.size())

torch.Size([2, 3])
torch.Size([1, 2, 3])


In [20]:
a = torch.randn(4,5)
print(torch.transpose(a,0,1).size())

torch.Size([5, 4])


In [0]:
import torch
x = torch.randn(10,1)
h = torch.randn(20,1)
W_h = torch.randn(20,20)
W_x = torch.randn(20,10)
i2h = torch.mm(W_x,x)
h2h = torch.mm(W_h,h)
next_h = i2h + h2h
next_h = torch.tanh(next_h)

In [23]:
import torch
import torch.nn as nn
fc = nn.Linear(4,5)
i = torch.randn(3,4)
o = fc(i)
print(o)

tensor([[-0.6190, -0.5785,  0.4807, -0.1141,  0.6463],
        [ 0.4987,  0.2471, -0.2677,  0.5721, -0.9516],
        [-0.2149,  0.1143,  0.2053,  0.5801,  0.0095]],
       grad_fn=<AddmmBackward>)


In [24]:
import torch
import torch.nn as nn
c1 = nn.Conv2d(3, 4, 3, stride=2, padding=2, dilation=2)
i = torch.randn(1, 3, 4, 4)
o = c1(i)
print(o.size())

torch.Size([1, 4, 2, 2])


In [27]:
import torch
import torch.nn as nn
rnn = nn.LSTM(5, 6, 2, batch_first=True, bidirectional=True)
i = torch.randn(3, 4, 5)
o, (h, c) = rnn(i)
print(o.size())

torch.Size([3, 4, 12])


In [0]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.conv1 = nn.Conv2d(3, 6, 5)
    self.pool = nn.MaxPool2d(2, 2)
    self.conv2 = nn.Conv2d(6, 16, 5)
    self.fc1 = nn.Linear(16 * 5 * 5,120)
    self.fc2 = nn.Linear(120, 84)
    self.fc3 = nn.Linear(84, 10)
  def forward(self, x):
    x = self.pool(F.relu(self.conv1(x)))
    x = self.pool(F.relu(self.conv2(x)))
    x = x.view(-1, 16 * 5 * 5)
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.fc3(x)
    return x
net = Net()

In [30]:
x = torch.randn(1, 3, 32, 32)
output = net(x)
target = torch.LongTensor([1])
criterion = nn.CrossEntropyLoss()
loss = criterion(output, target)
print(loss)

tensor(2.3651, grad_fn=<NllLossBackward>)


In [1]:
optimizer = torch.optim.SGD_(net.parameter(), lr =0.001)
optimizer.zero_grad()
loss.backward()
optimizer.step()
print(net.conv1.weight.grad)

NameError: ignored